# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meshCreation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import logging
import pygimli as pg
import pybert as pb
import pygimli.meshtools as mt
import matplotlib.pyplot as plt
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QGraphicsScene, QGraphicsView, QGraphicsPathItem, QVBoxLayout, QWidget, QGraphicsPixmapItem
from pygimli.physics import ert
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1174, 764)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QTabBar::tab:selected {\n"
"    background: lightblue;\n"
"    color: black;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    background: lightgray;\n"
"    color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(0, 0, 801, 591))
        self.verticalWidget.setObjectName("verticalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalWidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(781, 571))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Importing = QtWidgets.QWidget()
        self.Importing.setObjectName("Importing")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Importing)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Importing)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.gridLayout = QtWidgets.QGridLayout(self.Data)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.Data)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Data)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.Data)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.Data, "")
        self.Pre_processing = QtWidgets.QWidget()
        self.Pre_processing.setObjectName("Pre_processing")
        self.pushButton_2 = QtWidgets.QPushButton(self.Pre_processing)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listView = QtWidgets.QListView(self.Pre_processing)
        self.listView.setGeometry(QtCore.QRect(20, 50, 711, 431))
        self.listView.setObjectName("listView")
        self.tabWidget_2.addTab(self.Pre_processing, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.Importing, "")
        self.Domain_Mesh = QtWidgets.QWidget()
        self.Domain_Mesh.setObjectName("Domain_Mesh")
        self.verticalWidget_2 = QtWidgets.QWidget(self.Domain_Mesh)
        self.verticalWidget_2.setGeometry(QtCore.QRect(760, 220, 801, 591))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.verticalWidget_2)
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.verticalWidget_2)
        self.tabWidget_4.setMinimumSize(QtCore.QSize(781, 571))
        self.tabWidget_4.setMouseTracking(True)
        self.tabWidget_4.setAutoFillBackground(True)
        self.tabWidget_4.setStyleSheet("")
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.Importing_2 = QtWidgets.QWidget()
        self.Importing_2.setObjectName("Importing_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Importing_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget_5 = QtWidgets.QTabWidget(self.Importing_2)
        self.tabWidget_5.setAutoFillBackground(False)
        self.tabWidget_5.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.tabWidget_5.setObjectName("tabWidget_5")
        self.Data_2 = QtWidgets.QWidget()
        self.Data_2.setObjectName("Data_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Data_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_13 = QtWidgets.QPushButton(self.Data_2)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_2.addWidget(self.pushButton_13, 0, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.Data_2)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_2.addWidget(self.pushButton_14, 0, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Data_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.tabWidget_5.addTab(self.Data_2, "")
        self.Pre_processing_2 = QtWidgets.QWidget()
        self.Pre_processing_2.setObjectName("Pre_processing_2")
        self.pushButton_15 = QtWidgets.QPushButton(self.Pre_processing_2)
        self.pushButton_15.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.pushButton_15.setObjectName("pushButton_15")
        self.listView_7 = QtWidgets.QListView(self.Pre_processing_2)
        self.listView_7.setGeometry(QtCore.QRect(20, 50, 711, 431))
        self.listView_7.setObjectName("listView_7")
        self.tabWidget_5.addTab(self.Pre_processing_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget_5)
        self.tabWidget_4.addTab(self.Importing_2, "")
        self.Domain_Mesh_2 = QtWidgets.QWidget()
        self.Domain_Mesh_2.setObjectName("Domain_Mesh_2")
        self.listView_8 = QtWidgets.QListView(self.Domain_Mesh_2)
        self.listView_8.setGeometry(QtCore.QRect(0, 170, 701, 341))
        self.listView_8.setObjectName("listView_8")
        self.textEdit_3 = QtWidgets.QTextEdit(self.Domain_Mesh_2)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 40, 131, 51))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.Domain_Mesh_2)
        self.textEdit_4.setGeometry(QtCore.QRect(40, 110, 131, 51))
        self.textEdit_4.setObjectName("textEdit_4")
        self.spinBox_5 = QtWidgets.QSpinBox(self.Domain_Mesh_2)
        self.spinBox_5.setGeometry(QtCore.QRect(190, 40, 51, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.spinBox_5.sizePolicy().hasHeightForWidth())
        self.spinBox_5.setSizePolicy(sizePolicy)
        self.spinBox_5.setObjectName("spinBox_5")
        self.textEdit_12 = QtWidgets.QTextEdit(self.Domain_Mesh_2)
        self.textEdit_12.setGeometry(QtCore.QRect(270, 50, 131, 51))
        self.textEdit_12.setObjectName("textEdit_12")
        self.textEdit_6 = QtWidgets.QTextEdit(self.Domain_Mesh_2)
        self.textEdit_6.setGeometry(QtCore.QRect(270, 90, 131, 51))
        self.textEdit_6.setObjectName("textEdit_6")
        self.pushButton_16 = QtWidgets.QPushButton(self.Domain_Mesh_2)
        self.pushButton_16.setGeometry(QtCore.QRect(500, 20, 161, 51))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.Domain_Mesh_2)
        self.pushButton_17.setGeometry(QtCore.QRect(500, 90, 161, 51))
        self.pushButton_17.setObjectName("pushButton_17")
        self.spinBox_6 = QtWidgets.QSpinBox(self.Domain_Mesh_2)
        self.spinBox_6.setGeometry(QtCore.QRect(190, 90, 51, 21))
        self.spinBox_6.setMinimumSize(QtCore.QSize(51, 21))
        self.spinBox_6.setObjectName("spinBox_6")
        self.spinBox_7 = QtWidgets.QSpinBox(self.Domain_Mesh_2)
        self.spinBox_7.setGeometry(QtCore.QRect(190, 50, 51, 21))
        self.spinBox_7.setObjectName("spinBox_7")
        self.spinBox_9 = QtWidgets.QSpinBox(self.Domain_Mesh_2)
        self.spinBox_9.setGeometry(QtCore.QRect(190, 110, 51, 21))
        self.spinBox_9.setObjectName("spinBox_9")
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.Domain_Mesh_2)
        self.doubleSpinBox_4.setGeometry(QtCore.QRect(410, 30, 62, 22))
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.doubleSpinBox_5 = QtWidgets.QDoubleSpinBox(self.Domain_Mesh_2)
        self.doubleSpinBox_5.setGeometry(QtCore.QRect(410, 100, 62, 22))
        self.doubleSpinBox_5.setObjectName("doubleSpinBox_5")
        self.tabWidget_4.addTab(self.Domain_Mesh_2, "")
        self.Inversion_2 = QtWidgets.QWidget()
        self.Inversion_2.setObjectName("Inversion_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.Inversion_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 30, 411, 73))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.textEdit_13 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_13.setObjectName("textEdit_13")
        self.horizontalLayout_6.addWidget(self.textEdit_13)
        self.spinBox_12 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_12.setObjectName("spinBox_12")
        self.horizontalLayout_6.addWidget(self.spinBox_12)
        self.textEdit_14 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_14.setObjectName("textEdit_14")
        self.horizontalLayout_6.addWidget(self.textEdit_14)
        self.spinBox_13 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_13.setObjectName("spinBox_13")
        self.horizontalLayout_6.addWidget(self.spinBox_13)
        self.textEdit_15 = QtWidgets.QTextEdit(self.layoutWidget_3)
        self.textEdit_15.setObjectName("textEdit_15")
        self.horizontalLayout_6.addWidget(self.textEdit_15)
        self.spinBox_14 = QtWidgets.QSpinBox(self.layoutWidget_3)
        self.spinBox_14.setObjectName("spinBox_14")
        self.horizontalLayout_6.addWidget(self.spinBox_14)
        self.pushButton_18 = QtWidgets.QPushButton(self.Inversion_2)
        self.pushButton_18.setGeometry(QtCore.QRect(440, 10, 111, 41))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.Inversion_2)
        self.pushButton_19.setGeometry(QtCore.QRect(440, 60, 111, 41))
        self.pushButton_19.setObjectName("pushButton_19")
        self.listView_9 = QtWidgets.QListView(self.Inversion_2)
        self.listView_9.setGeometry(QtCore.QRect(30, 110, 711, 431))
        self.listView_9.setObjectName("listView_9")
        self.tabWidget_4.addTab(self.Inversion_2, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textEdit_16 = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_16.setGeometry(QtCore.QRect(0, 10, 111, 31))
        self.textEdit_16.setObjectName("textEdit_16")
        self.listView_10 = QtWidgets.QListView(self.tab_6)
        self.listView_10.setGeometry(QtCore.QRect(0, 60, 711, 431))
        self.listView_10.setObjectName("listView_10")
        self.doubleSpinBox_6 = QtWidgets.QDoubleSpinBox(self.tab_6)
        self.doubleSpinBox_6.setGeometry(QtCore.QRect(120, 10, 71, 31))
        self.doubleSpinBox_6.setDecimals(1)
        self.doubleSpinBox_6.setSingleStep(0.1)
        self.doubleSpinBox_6.setProperty("value", 25.0)
        self.doubleSpinBox_6.setObjectName("doubleSpinBox_6")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_20.setGeometry(QtCore.QRect(200, 10, 81, 31))
        self.pushButton_20.setObjectName("pushButton_20")
        self.tabWidget_4.addTab(self.tab_6, "")
        self.Visualization_2 = QtWidgets.QWidget()
        self.Visualization_2.setObjectName("Visualization_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.Visualization_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.tabWidget_6 = QtWidgets.QTabWidget(self.Visualization_2)
        self.tabWidget_6.setObjectName("tabWidget_6")
        self.Resistivity_2 = QtWidgets.QWidget()
        self.Resistivity_2.setObjectName("Resistivity_2")
        self.pushButton_21 = QtWidgets.QPushButton(self.Resistivity_2)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 10, 91, 31))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.Resistivity_2)
        self.pushButton_22.setGeometry(QtCore.QRect(110, 10, 111, 31))
        self.pushButton_22.setObjectName("pushButton_22")
        self.listView_11 = QtWidgets.QListView(self.Resistivity_2)
        self.listView_11.setGeometry(QtCore.QRect(30, 50, 711, 431))
        self.listView_11.setObjectName("listView_11")
        self.tabWidget_6.addTab(self.Resistivity_2, "")
        self.Water_content_2 = QtWidgets.QWidget()
        self.Water_content_2.setObjectName("Water_content_2")
        self.pushButton_23 = QtWidgets.QPushButton(self.Water_content_2)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 10, 81, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.Water_content_2)
        self.pushButton_24.setGeometry(QtCore.QRect(100, 10, 71, 31))
        self.pushButton_24.setObjectName("pushButton_24")
        self.listView_12 = QtWidgets.QListView(self.Water_content_2)
        self.listView_12.setGeometry(QtCore.QRect(20, 50, 711, 431))
        self.listView_12.setObjectName("listView_12")
        self.tabWidget_6.addTab(self.Water_content_2, "")
        self.horizontalLayout_7.addWidget(self.tabWidget_6)
        self.tabWidget_4.addTab(self.Visualization_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget_4)
        self.meshView = QtWidgets.QTabWidget(self.Domain_Mesh)
        self.meshView.setGeometry(QtCore.QRect(0, 0, 781, 571))
        font = QtGui.QFont()
        font.setPointSize(8)

        '''
        Below is the code for creating a domain and mesh.
        '''

        '''Set up the domain'''
        self.meshView.setFont(font)
        self.meshView.setObjectName("meshView")
        mesh_view_layout = self.meshView.layout()

        self.Mesh = QtWidgets.QWidget()
        self.Mesh.setObjectName("Mesh")
        self.start = QtWidgets.QTextEdit(self.Mesh)
        self.start.setGeometry(QtCore.QRect(200, 40, 131, 41))
        self.start.setObjectName("start")
        self.end = QtWidgets.QTextEdit(self.Mesh)
        self.end.setGeometry(QtCore.QRect(200, 90, 131, 41))
        self.end.setObjectName("end")
        self.startY = QtWidgets.QSpinBox(self.Mesh)
        self.startY.setGeometry(QtCore.QRect(350, 60, 51, 21))
        self.startY.setObjectName("startY")
        self.startX = QtWidgets.QSpinBox(self.Mesh)

        self.startX.setGeometry(QtCore.QRect(350, 40, 51, 21))
        self.startX.setObjectName("startX")
        self.startX.setSizePolicy(sizePolicy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(4)
        sizePolicy.setHeightForWidth(self.startX.sizePolicy().hasHeightForWidth())
        self.endX = QtWidgets.QSpinBox(self.Mesh)
        self.endX.setGeometry(QtCore.QRect(350, 90, 51, 21))
        self.endX.setObjectName("endX")
        self.endX.setMinimumSize(QtCore.QSize(51, 21))
        self.endY = QtWidgets.QSpinBox(self.Mesh)
        self.endY.setGeometry(QtCore.QRect(350, 110, 51, 21))
        self.endY.setObjectName("endY")


        '''Apply button for Domain'''
        self.applyButton_1 = QtWidgets.QPushButton(self.Mesh)
        self.applyButton_1.setGeometry(QtCore.QRect(440, 30, 161, 51))
        self.applyButton_1.setObjectName("applyButton_1")
        font = QtGui.QFont()
        font.setPointSize(7)

        '''Save button for Domain'''
        self.saveButton_1 = QtWidgets.QPushButton("Save", self.Mesh)
        self.saveButton_1.setGeometry(QtCore.QRect(440, 90, 161, 51))
        self.saveButton_1.setObjectName("saveButton_1")
        self.saveButton_1.clicked.connect(self.save)

        '''Present the figure for Domain'''
        self.domainView = QtWidgets.QGraphicsView(self.Mesh)
        self.domainView.setGeometry(QtCore.QRect(150, 161, 500, 350))
        self.domainView.setObjectName("domainView")
        domainView_layout = QtWidgets.QVBoxLayout(self.domainView)  # Create a QVBoxLayout
        self.canvas_domain = FigureCanvas(plt.figure())
        domainView_layout.addWidget(self.canvas_domain)
        self.applyButton_1.clicked.connect(self.create_domain)


        '''Set up the mesh'''
        self.meshView.addTab(self.Mesh, "")
        self.Mesh1 = QtWidgets.QWidget()
        self.Mesh1.setObjectName("Mesh1")
        self.quality_para = QtWidgets.QTextEdit(self.Mesh1)
        self.quality_para.setGeometry(QtCore.QRect(200, 40, 131, 41))
        self.quality_para.setObjectName("quality_para")
        self.area_para = QtWidgets.QTextEdit(self.Mesh1)
        self.area_para.setGeometry(QtCore.QRect(200, 90, 131, 41))
        self.area_para.setObjectName("area_para")
        self.quality = QtWidgets.QDoubleSpinBox(self.Mesh1)
        self.quality.setGeometry(QtCore.QRect(350, 45, 62, 22))
        self.quality.setSingleStep(0.01)
        self.quality.setObjectName("quality")
        self.area = QtWidgets.QDoubleSpinBox(self.Mesh1)
        self.area.setGeometry(QtCore.QRect(350, 100, 62, 22))
        self.area.setSingleStep(0.01)
        self.area.setObjectName("area")

        '''Apply button for Mesh'''
        self.applyButton_2 = QtWidgets.QPushButton(self.Mesh1)
        self.applyButton_2.setGeometry(QtCore.QRect(440, 30, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.applyButton_2.setFont(font)
        self.applyButton_2.setObjectName("applyButton_2")
        self.applyButton_2.clicked.connect(self.create_mesh)

        '''Save button for Mesh'''
        self.saveButton_2 = QtWidgets.QPushButton("Save", self.Mesh1)
        self.saveButton_2.setGeometry(QtCore.QRect(440, 90, 161, 51))
        self.saveButton_2.setObjectName("saveButton_2")
        self.saveButton_2.clicked.connect(self.save)

        '''Present the figure for Mesh'''
        self.meshView.addTab(self.Mesh1, "")
        self.domainView_2 = QtWidgets.QGraphicsView(self.Mesh1)
        self.domainView_2.setGeometry(QtCore.QRect(150, 161, 500, 350))
        self.domainView_2.setObjectName("domainView_2")
        domainView_2_layout = QtWidgets.QVBoxLayout(self.domainView_2)  # Create a QVBoxLayout
        self.canvas_mesh = FigureCanvas(plt.figure())
        domainView_2_layout.addWidget(self.canvas_mesh)
        self.applyButton_1.clicked.connect(self.create_mesh)


        #Choose a Resistivity Measurement Method

        '''Apply button for WA method'''
        self.RMM = QtWidgets.QWidget()
        self.RMM.setObjectName("RMM")
        self.waButton = QtWidgets.QPushButton(self.RMM)
        self.waButton.setGeometry(QtCore.QRect(280, 45, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.waButton.setFont(font)
        self.waButton.setObjectName("waButton")


        '''Apply button for DD method '''
        self.ddButton = QtWidgets.QPushButton(self.RMM)
        self.ddButton.setGeometry(QtCore.QRect(280, 75, 150, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.ddButton.setFont(font)
        self.ddButton.setObjectName("ddButton")
        self.ddButton.clicked.connect(self.dd_method)

        '''Next button'''
        self.pushButton_4 = QtWidgets.QPushButton(self.RMM)
        self.pushButton_4.setGeometry(QtCore.QRect(450, 55, 91, 31))
        self.pushButton_4.setStyleSheet("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.jump_to_next_page)


        '''Present the figure for DD method'''
        self.meshView.addTab(self.RMM, "")
        '''self.meshView.raise_()'''
        '''self.verticalWidget_2.raise_()'''
        self.tabWidget.addTab(self.Domain_Mesh, "")

        self.domainView_3 = QtWidgets.QGraphicsView(self.RMM)
        self.domainView_3.setGeometry(QtCore.QRect(150, 150, 500, 350))
        self.domainView_3.setObjectName("domainView_3")

        ddView_layout = QtWidgets.QVBoxLayout(self.domainView_3)
        self.canvas_dd = FigureCanvas(plt.figure())
        ddView_layout.addWidget(self.canvas_dd)


        '''Inversion'''
        self.Inversion = QtWidgets.QWidget()
        self.Inversion.setObjectName("Inversion")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Inversion)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 411, 73))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_8 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_4.addWidget(self.textEdit_8)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_4.addWidget(self.spinBox_8)
        self.textEdit_9 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_4.addWidget(self.textEdit_9)
        self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_4.addWidget(self.spinBox_11)
        self.textEdit_10 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_4.addWidget(self.textEdit_10)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_4.addWidget(self.spinBox_10)
        self.pushButton_5 = QtWidgets.QPushButton(self.Inversion)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 10, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.Inversion)
        self.pushButton_9.setGeometry(QtCore.QRect(440, 60, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.listView_3 = QtWidgets.QListView(self.Inversion)
        self.listView_3.setGeometry(QtCore.QRect(30, 110, 711, 431))
        self.listView_3.setObjectName("listView_3")
        self.tabWidget.addTab(self.Inversion, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_11.setGeometry(QtCore.QRect(0, 10, 111, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.listView_6 = QtWidgets.QListView(self.tab_5)
        self.listView_6.setGeometry(QtCore.QRect(0, 60, 711, 431))
        self.listView_6.setObjectName("listView_6")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(120, 10, 71, 31))
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 25.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_12.setGeometry(QtCore.QRect(200, 10, 81, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_5, "")
        self.Visualization = QtWidgets.QWidget()
        self.Visualization.setObjectName("Visualization")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Visualization)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.Visualization)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.Resistivity = QtWidgets.QWidget()
        self.Resistivity.setObjectName("Resistivity")
        self.pushButton_7 = QtWidgets.QPushButton(self.Resistivity)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 10, 91, 31))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.Resistivity)
        self.pushButton_10.setGeometry(QtCore.QRect(110, 10, 111, 31))
        self.pushButton_10.setObjectName("pushButton_10")
        self.listView_4 = QtWidgets.QListView(self.Resistivity)
        self.listView_4.setGeometry(QtCore.QRect(30, 50, 711, 431))
        self.listView_4.setObjectName("listView_4")
        self.tabWidget_3.addTab(self.Resistivity, "")
        self.Water_content = QtWidgets.QWidget()
        self.Water_content.setObjectName("Water_content")
        self.pushButton_6 = QtWidgets.QPushButton(self.Water_content)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 10, 81, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_11 = QtWidgets.QPushButton(self.Water_content)
        self.pushButton_11.setGeometry(QtCore.QRect(100, 10, 71, 31))
        self.pushButton_11.setObjectName("pushButton_11")
        self.listView_5 = QtWidgets.QListView(self.Water_content)
        self.listView_5.setGeometry(QtCore.QRect(20, 50, 711, 431))
        self.listView_5.setObjectName("listView_5")
        self.tabWidget_3.addTab(self.Water_content, "")
        self.horizontalLayout_5.addWidget(self.tabWidget_3)
        self.tabWidget.addTab(self.Visualization, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1174, 22))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionGuidline = QtWidgets.QAction(MainWindow)
        self.actionGuidline.setObjectName("actionGuidline")
        self.actionContract = QtWidgets.QAction(MainWindow)
        self.actionContract.setObjectName("actionContract")
        self.menuProject.addAction(self.actionNew)
        self.menuProject.addAction(self.actionOpen)
        self.menuProject.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionGuidline)
        self.menuHelp.addAction(self.actionContract)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_4.setCurrentIndex(1)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget_6.setCurrentIndex(1)
        self.meshView.setCurrentIndex(2)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    '''Function to create a domain'''

    def create_domain(self):
        start_x = self.startX.value()
        start_y = self.startY.value()
        end_x = self.endX.value()
        end_y = self.endY.value()

        self.geom = pg.meshtools.createWorld(start=[start_x, start_y], end=[end_x, end_y], worldMarker=False)
        ax = self.canvas_domain.figure.add_subplot(111)
        ax.clear()
        pg.show(self.geom, ax=ax, boundary=True)
        self.canvas_domain.draw()

    '''Function to create a mesh'''
    def create_mesh(self):
        pg.show(self.geom, boundary=True)
        quality = self.quality.value()
        area = self.area.value()

        mesh = mt.createMesh(self.geom, quality, area, smooth=True)
        ab = self.canvas_mesh.figure.add_subplot(111)
        ab.clear()
        pg.show(mesh, ax=ab, boundary=True)
        self.canvas_mesh.draw()

    "Function to save generated figures"
    def save(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.ReadOnly
        file_name, _ = QtWidgets.QFileDialog.getSaveFileName(
                    None, "Save Figure", "", "PNG Files (*.png);;All Files (*)", options=options
            )
        if file_name:
                # Save the figure as a PNG file
                self.geom.savefig(file_name, format="png")


    '''DD method'''
    def dd_method(self):
        world = mt.createWorld(start=[-50, 0], end=[50, -50], layers=[-1, -5],
                           worldMarker=True)
        block = mt.createCircle(pos=[0, -3.], radius=1, marker=4,
                            boundaryMarker=10, area=0.1)
        # Merge geometry definition into a Piecewise Linear Complex (PLC)
        geom = mt.mergePLC([world, block])

        scheme = pb.createData(elecs=pg.utils.grange(start=-10, end=10, n=21),
                               schemeName='dd')
        for pos in scheme.sensorPositions():
                geom.createNode(pos)
                geom.createNode(pos + pg.RVector3(0, -0.1))

        # Create a mesh for the finite element modelling with appropriate mesh quality.
        mesh = mt.createMesh(geom, quality=34)

        # Create a map to set resistivity values in the appropriate regions
        # [[regionNumber, resistivity], [regionNumber, resistivity], [...]
        rhomap = [[1, 100.],
                  [2, 50.],
                  [3, 10.],
                  [4, 100.]]

        ert = pb.ERTManager
        data = ert.simulate(mesh, res=rhomap, scheme=scheme, noiseLevel=1,
                            noiseAbs=1e-6)

        print('Simulated rhoa', data('rhoa'), max(data('rhoa')))
        data.markInvalid(data('rhoa') < 0)
        print('Filtered rhoa', data('rhoa'), max(data('rhoa')))
        data.removeInvalid()
        data.save('simple.dat')


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Import"))
        self.pushButton.setText(_translate("MainWindow", "Choose your file"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Data), _translate("MainWindow", "Data"))
        self.pushButton_2.setText(_translate("MainWindow", "Clean Data"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Pre_processing), _translate("MainWindow", "Pre_processing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Importing), _translate("MainWindow", "Importing"))
        self.pushButton_13.setText(_translate("MainWindow", "Import"))
        self.pushButton_14.setText(_translate("MainWindow", "Choose your file"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.Data_2), _translate("MainWindow", "Data"))
        self.pushButton_15.setText(_translate("MainWindow", "Clean Data"))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.Pre_processing_2), _translate("MainWindow", "Pre_processing"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.Importing_2), _translate("MainWindow", "Importing"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">Start</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">End</span></p></body></html>"))
        self.textEdit_12.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">Quality</span></p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:10pt;\">Area</span></p></body></html>"))
        self.pushButton_16.setText(_translate("MainWindow", "Apply"))
        self.pushButton_17.setText(_translate("MainWindow", "Save"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.Domain_Mesh_2), _translate("MainWindow", "Domain and Mesh"))
        self.textEdit_13.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">maxIter:</span></p></body></html>"))
        self.textEdit_14.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">Lam:</span></p></body></html>"))
        self.textEdit_15.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">dPhi:</span></p></body></html>"))
        self.pushButton_18.setText(_translate("MainWindow", "Apply"))
        self.pushButton_19.setText(_translate("MainWindow", "Save"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.Inversion_2), _translate("MainWindow", "Inversion"))
        self.textEdit_16.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Temperture</span></p></body></html>"))
        self.pushButton_20.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_6), _translate("MainWindow", "Water Content"))
        self.pushButton_21.setText(_translate("MainWindow", "Result"))
        self.pushButton_22.setText(_translate("MainWindow", "Save"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.Resistivity_2), _translate("MainWindow", "Resistivity"))
        self.pushButton_23.setText(_translate("MainWindow", "Convert"))
        self.pushButton_24.setText(_translate("MainWindow", "Save"))
        self.tabWidget_6.setTabText(self.tabWidget_6.indexOf(self.Water_content_2), _translate("MainWindow", "Water content"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.Visualization_2), _translate("MainWindow", "Visualization"))
        self.start.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:8pt;\">Start</span></p></body></html>"))
        self.end.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:8pt;\">End</span></p></body></html>"))
        self.applyButton_1.setText(_translate("MainWindow", "Apply"))
        self.meshView.setTabText(self.meshView.indexOf(self.Mesh), _translate("MainWindow", "Domain"))
        self.quality_para.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:8pt;\">Quality</span></p></body></html>"))
        self.area_para.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:8pt;\">Area</span></p></body></html>"))
        self.applyButton_2.setText(_translate("MainWindow", "Apply"))
        self.meshView.setTabText(self.meshView.indexOf(self.Mesh1), _translate("MainWindow", "Mesh"))
        self.waButton.setText(_translate("MainWindow", "Wenner Array (WA)"))
        self.ddButton.setText(_translate("MainWindow", "Dipole-Dipole (DD)"))
        self.pushButton_4.setText(_translate("MainWindow", "Next"))
        self.meshView.setTabText(self.meshView.indexOf(self.RMM), _translate("MainWindow", "Resistivity Measurement Method"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Domain_Mesh), _translate("MainWindow", "Domain and Mesh"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">maxIter:</span></p></body></html>"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">Lam:</span></p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:9pt;\">dPhi:</span></p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Apply"))
        self.pushButton_9.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inversion), _translate("MainWindow", "Inversion"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Temperture</span></p></body></html>"))
        self.pushButton_12.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Water Content"))
        self.pushButton_7.setText(_translate("MainWindow", "Result"))
        self.pushButton_10.setText(_translate("MainWindow", "Save"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Resistivity), _translate("MainWindow", "Resistivity"))
        self.pushButton_6.setText(_translate("MainWindow", "Convert"))
        self.pushButton_11.setText(_translate("MainWindow", "Save"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.Water_content), _translate("MainWindow", "Water content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visualization), _translate("MainWindow", "Visualization"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionGuidline.setText(_translate("MainWindow", "Guidline"))
        self.actionContract.setText(_translate("MainWindow", "Contract"))

    def jump_to_next_page(self):
            index_of_page = 2
            # Switch to the desired page
            self.tabWidget_Importing.setCurrentIndex(index_of_page)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
