# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'soilColor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5.QtWidgets import (QtCore, QtGui, QApplication, QWidget, QVBoxLayout,
                             QRadioButton, QStackedWidget, QListView, QLabel,
                             QFileDialog, QApplication, QMainWindow, QWidget,
                             QHBoxLayout, QListWidget, QFileDialog, QCheckBox, QAction)
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import os
import imageio
from PyQt5.QtGui import QPixmap, QImageReader
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QStringListModel, QPixmap, QImage
from PyQt5.QtCore import QSortFilterProxyModel, Qt, QTimer
import glob
import cv2


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(981, 754)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QTabBar::tab:selected {\n"
"    background: lightblue;\n"
"    color: black;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"    background: lightgray;\n"
"    color: black;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setGeometry(QtCore.QRect(40, 40, 801, 591))
        self.verticalWidget.setObjectName("verticalWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.verticalWidget)
        self.horizontalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.verticalWidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(781, 571))
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.Importing = QtWidgets.QWidget()
        self.Importing.setObjectName("Importing")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Importing)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.Importing)
        self.tabWidget_2.setAutoFillBackground(False)
        self.tabWidget_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.Data = QtWidgets.QWidget()
        self.Data.setObjectName("Data")
        self.gridLayout = QtWidgets.QGridLayout(self.Data)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(self.Data)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.Data)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.Data)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.tabWidget_2.addTab(self.Data, "")
        self.Pre_processing = QtWidgets.QWidget()
        self.Pre_processing.setObjectName("Pre_processing")
        self.pushButton_2 = QtWidgets.QPushButton(self.Pre_processing)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 10, 81, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.listView = QtWidgets.QListView(self.Pre_processing)
        self.listView.setGeometry(QtCore.QRect(20, 50, 711, 431))
        self.listView.setObjectName("listView")
        self.tabWidget_2.addTab(self.Pre_processing, "")
        self.verticalLayout.addWidget(self.tabWidget_2)
        self.tabWidget.addTab(self.Importing, "")
        self.Domain_Mesh = QtWidgets.QWidget()
        self.Domain_Mesh.setObjectName("Domain_Mesh")
        self.pushButton_4 = QtWidgets.QPushButton(self.Domain_Mesh)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 50, 111, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.Domain_Mesh)
        self.pushButton_8.setGeometry(QtCore.QRect(440, 110, 111, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.listView_2 = QtWidgets.QListView(self.Domain_Mesh)
        self.listView_2.setGeometry(QtCore.QRect(30, 180, 701, 361))
        self.listView_2.setObjectName("listView_2")
        self.layoutWidget = QtWidgets.QWidget(self.Domain_Mesh)
        self.layoutWidget.setGeometry(QtCore.QRect(19, 15, 730, 187))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEdit_3 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_3.setObjectName("textEdit_3")
        self.horizontalLayout.addWidget(self.textEdit_3)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout.addWidget(self.textEdit)
        self.spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout.addWidget(self.spinBox)
        self.spinBox_3 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_3.setObjectName("spinBox_3")
        self.horizontalLayout.addWidget(self.spinBox_3)
        self.textEdit_2 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout.addWidget(self.textEdit_2)
        self.spinBox_2 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_2.setObjectName("spinBox_2")
        self.horizontalLayout.addWidget(self.spinBox_2)
        self.spinBox_4 = QtWidgets.QSpinBox(self.layoutWidget)
        self.spinBox_4.setObjectName("spinBox_4")
        self.horizontalLayout.addWidget(self.spinBox_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_4.setObjectName("textEdit_4")
        self.horizontalLayout_3.addWidget(self.textEdit_4)
        self.textEdit_5 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_5.setObjectName("textEdit_5")
        self.horizontalLayout_3.addWidget(self.textEdit_5)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox)
        self.textEdit_6 = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit_6.setObjectName("textEdit_6")
        self.horizontalLayout_3.addWidget(self.textEdit_6)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.Domain_Mesh, "")
        self.Inversion = QtWidgets.QWidget()
        self.Inversion.setObjectName("Inversion")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Inversion)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 436, 89))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.textEdit_8 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_8.setObjectName("textEdit_8")
        self.horizontalLayout_4.addWidget(self.textEdit_8)
        self.spinBox_8 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_8.setObjectName("spinBox_8")
        self.horizontalLayout_4.addWidget(self.spinBox_8)
        self.textEdit_9 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_9.setObjectName("textEdit_9")
        self.horizontalLayout_4.addWidget(self.textEdit_9)
        self.spinBox_11 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_11.setObjectName("spinBox_11")
        self.horizontalLayout_4.addWidget(self.spinBox_11)
        self.textEdit_10 = QtWidgets.QTextEdit(self.layoutWidget_2)
        self.textEdit_10.setObjectName("textEdit_10")
        self.horizontalLayout_4.addWidget(self.textEdit_10)
        self.spinBox_10 = QtWidgets.QSpinBox(self.layoutWidget_2)
        self.spinBox_10.setObjectName("spinBox_10")
        self.horizontalLayout_4.addWidget(self.spinBox_10)
        self.pushButton_5 = QtWidgets.QPushButton(self.Inversion)
        self.pushButton_5.setGeometry(QtCore.QRect(440, 10, 111, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_9 = QtWidgets.QPushButton(self.Inversion)
        self.pushButton_9.setGeometry(QtCore.QRect(440, 60, 111, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.listView_3 = QtWidgets.QListView(self.Inversion)
        self.listView_3.setGeometry(QtCore.QRect(30, 110, 711, 431))
        self.listView_3.setObjectName("listView_3")
        self.tabWidget.addTab(self.Inversion, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.textEdit_11 = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_11.setGeometry(QtCore.QRect(0, 10, 111, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.listView_6 = QtWidgets.QListView(self.tab_5)
        self.listView_6.setGeometry(QtCore.QRect(0, 60, 711, 431))
        self.listView_6.setObjectName("listView_6")
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.tab_5)
        self.doubleSpinBox_3.setGeometry(QtCore.QRect(120, 10, 71, 31))
        self.doubleSpinBox_3.setDecimals(1)
        self.doubleSpinBox_3.setSingleStep(0.1)
        self.doubleSpinBox_3.setProperty("value", 25.0)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_12.setGeometry(QtCore.QRect(200, 10, 81, 31))
        self.pushButton_12.setObjectName("pushButton_12")
        self.tabWidget.addTab(self.tab_5, "")



        self.Visualization = QtWidgets.QWidget()
        self.Visualization.setObjectName("Visualization")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Visualization)

        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tabWidget_Vis_Wat = QtWidgets.QTabWidget(self.Visualization)
        self.tabWidget_Vis_Wat.setObjectName("tabWidget_Vis_Wat")
        self.Resistivity = QtWidgets.QWidget()
        self.Resistivity.setObjectName("Resistivity")
        self.stackedWidget_Vis_Res_PagecSca = QtWidgets.QStackedWidget(self.Resistivity)
        self.stackedWidget_Vis_Res_PagecSca.setGeometry(QtCore.QRect(0, 40, 741, 441))
        self.stackedWidget_Vis_Res_PagecSca.setObjectName("stackedWidget_Vis_Res_PagecSca")

        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.graphicsView_Vis_Res_cSca_Disp = QtWidgets.QGraphicsView(self.page_7)

        self.graphicsView_Vis_Res_cSca_Disp.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Res_cSca_Disp.setObjectName("graphicsView_Vis_Res_cSca_Disp")

        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.page_7)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(460, 400, 261, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")

        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

        self.pushButton_Vis_Res_cSca_Replay_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Vis_Res_cSca_Replay_2.setObjectName("pushButton_Vis_Res_cSca_Replay_2")

        self.horizontalLayout_7.addWidget(self.pushButton_Vis_Res_cSca_Replay_2)
        self.pushButton_Vis_Res_cSca_Save_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_Vis_Res_cSca_Save_2.setObjectName("pushButton_Vis_Res_cSca_Save_2")
        self.horizontalLayout_7.addWidget(self.pushButton_Vis_Res_cSca_Save_2)

        self.verticalLayoutWidget = QtWidgets.QWidget(self.page_7)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.label_Vis_Res_cSca_fSele_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Vis_Res_cSca_fSele_2.setObjectName("label_Vis_Res_cSca_fSele_2")
        self.verticalLayout_3.addWidget(self.label_Vis_Res_cSca_fSele_2)

        self.listWidget_Vis_Res_cSca_fSele = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget_Vis_Res_cSca_fSele.setObjectName("listWidget_Vis_Res_cSca_fSele")
        self.verticalLayout_3.addWidget(self.listWidget_Vis_Res_cSca_fSele)

        self.label_Vis_Res_cSca_cSca = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_Vis_Res_cSca_cSca.setObjectName("label_Vis_Res_cSca_cSca")
        self.verticalLayout_3.addWidget(self.label_Vis_Res_cSca_cSca)

        self.listWidget_Vis_Res_cSca_cSca = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.listWidget_Vis_Res_cSca_cSca.setObjectName("listWidget_Vis_Res_cSca_cSca")
        self.verticalLayout_3.addWidget(self.listWidget_Vis_Res_cSca_cSca)

        self.pushButton_Vis_Res_cSca_Apply = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_Vis_Res_cSca_Apply.setObjectName("pushButton_Vis_Res_cSca_Apply")
        self.verticalLayout_3.addWidget(self.pushButton_Vis_Res_cSca_Apply)

        self.stackedWidget_Vis_Res_PagecSca.addWidget(self.page_7)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget_Vis_Res_7 = QtWidgets.QStackedWidget(self.page_3)
        self.stackedWidget_Vis_Res_7.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.stackedWidget_Vis_Res_7.setObjectName("stackedWidget_Vis_Res_7")

        self.page_17 = QtWidgets.QWidget()
        self.page_17.setObjectName("page_17")
        self.graphicsView_8 = QtWidgets.QGraphicsView(self.page_17)
        self.graphicsView_8.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_8.setObjectName("graphicsView_8")

        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.page_17)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")

        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")

        self.pushButton_26 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_12.addWidget(self.pushButton_26)

        self.pushButton_27 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_12.addWidget(self.pushButton_27)

        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.page_17)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")

        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")

        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_8.addWidget(self.label_11)

        self.listWidget_15 = QtWidgets.QListWidget(self.verticalLayoutWidget_6)
        self.listWidget_15.setObjectName("listWidget_15")
        self.verticalLayout_8.addWidget(self.listWidget_15)

        self.pushButton_28 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_8.addWidget(self.pushButton_28)

        self.stackedWidget_Vis_Res_7.addWidget(self.page_17)
        self.page_18 = QtWidgets.QWidget()
        self.page_18.setObjectName("page_18")

        self.stackedWidget_Vis_Res_PageAni = QtWidgets.QStackedWidget(self.page_18)
        self.stackedWidget_Vis_Res_PageAni.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.stackedWidget_Vis_Res_PageAni.setObjectName("stackedWidget_Vis_Res_PageAni")

        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.page_4)

        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")

        self.label_Vis_Res_fSele = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_Vis_Res_fSele.setObjectName("label_Vis_Res_fSele")
        self.verticalLayout_10.addWidget(self.label_Vis_Res_fSele)

        self.listWidget_Vis_Res_cSche_fSele = QtWidgets.QListWidget(self.verticalLayoutWidget_8)
        self.listWidget_Vis_Res_cSche_fSele.setObjectName("listWidget_Vis_Res_cSche_fSele")
        self.verticalLayout_10.addWidget(self.listWidget_Vis_Res_cSche_fSele)

        self.label_Vis_Res_cSche = QtWidgets.QLabel(self.verticalLayoutWidget_8)
        self.label_Vis_Res_cSche.setObjectName("label_Vis_Res_cSche")
        self.verticalLayout_10.addWidget(self.label_Vis_Res_cSche)

        self.listWidget_Vis_Res_cSche_cSche = QtWidgets.QListWidget(self.verticalLayoutWidget_8)
        self.listWidget_Vis_Res_cSche_cSche.setObjectName("listWidget_Vis_Res_cSche_cSche")
        self.verticalLayout_10.addWidget(self.listWidget_Vis_Res_cSche_cSche)

        self.pushButton_Vis_Res_cSche_Apply = QtWidgets.QPushButton(self.verticalLayoutWidget_8)
        self.pushButton_Vis_Res_cSche_Apply.setObjectName("pushButton_Vis_Res_cSche_Apply")
        self.verticalLayout_10.addWidget(self.pushButton_Vis_Res_cSche_Apply)

        self.graphicsView_Vis_Res_cSche_Disp = QtWidgets.QGraphicsView(self.page_4)
        self.graphicsView_Vis_Res_cSche_Disp.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Res_cSche_Disp.setObjectName("graphicsView_Vis_Res_cSche_Disp")

        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.page_4)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")

        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")

        self.pushButton_Vis_Res_cSche_Replay = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_Vis_Res_cSche_Replay.setObjectName("pushButton_Vis_Res_cSche_Replay")
        self.horizontalLayout_15.addWidget(self.pushButton_Vis_Res_cSche_Replay)

        self.pushButton_Vis_Res_cSche_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_10)
        self.pushButton_Vis_Res_cSche_Save.setObjectName("pushButton_Vis_Res_cSche_Save")
        self.horizontalLayout_15.addWidget(self.pushButton_Vis_Res_cSche_Save)

        self.stackedWidget_Vis_Res_PageAni.addWidget(self.page_4)
        self.page_19 = QtWidgets.QWidget()
        self.page_19.setObjectName("page_19")

        self.graphicsView_Vis_Res_cSca_Disp_2 = QtWidgets.QGraphicsView(self.page_19)
        self.graphicsView_Vis_Res_cSca_Disp_2.setGeometry(QtCore.QRect(140, 20, 591, 391))
        self.graphicsView_Vis_Res_cSca_Disp_2.setObjectName("graphicsView_Vis_Res_cSca_Disp_2")

        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.page_19)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")

        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")

        self.label_Vis_Res_cSca_fSele = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_Vis_Res_cSca_fSele.setObjectName("label_Vis_Res_cSca_fSele")
        self.verticalLayout_9.addWidget(self.label_Vis_Res_cSca_fSele)

        self.listWidget_Vis_Res_cSca_fSele_2 = QtWidgets.QListWidget(self.verticalLayoutWidget_7)
        self.listWidget_Vis_Res_cSca_fSele_2.setObjectName("listWidget_Vis_Res_cSca_fSele_2")
        self.verticalLayout_9.addWidget(self.listWidget_Vis_Res_cSca_fSele_2)

        self.label_Vis_Res_cSca_cSca_3 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.label_Vis_Res_cSca_cSca_3.setObjectName("label_Vis_Res_cSca_cSca_3")
        self.verticalLayout_9.addWidget(self.label_Vis_Res_cSca_cSca_3)

        self.listWidget_Vis_Res_cSca_cSca_3 = QtWidgets.QListWidget(self.verticalLayoutWidget_7)
        self.listWidget_Vis_Res_cSca_cSca_3.setObjectName("listWidget_Vis_Res_cSca_cSca_3")
        self.verticalLayout_9.addWidget(self.listWidget_Vis_Res_cSca_cSca_3)

        self.pushButton_Vis_Res_cSca_Apply_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        self.pushButton_Vis_Res_cSca_Apply_2.setObjectName("pushButton_Vis_Res_cSca_Apply_2")
        self.verticalLayout_9.addWidget(self.pushButton_Vis_Res_cSca_Apply_2)

        self.stackedWidget_Vis_Res_PageAni.addWidget(self.page_19)
        self.page_20 = QtWidgets.QWidget()
        self.page_20.setObjectName("page_20")

        self.verticalLayoutWidget_22 = QtWidgets.QWidget(self.page_20)
        self.verticalLayoutWidget_22.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_22.setObjectName("verticalLayoutWidget_22")

        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_22)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")

        self.label_Vis_Res_Ani_fSele = QtWidgets.QLabel(self.verticalLayoutWidget_22)
        self.label_Vis_Res_Ani_fSele.setObjectName("label_Vis_Res_Ani_fSele")
        self.verticalLayout_24.addWidget(self.label_Vis_Res_Ani_fSele)

        self.listWidget_Vis_Res_Ani_fSele = QtWidgets.QListWidget(self.verticalLayoutWidget_22)
        self.listWidget_Vis_Res_Ani_fSele.setObjectName("listWidget_Vis_Res_Ani_fSele")
        self.verticalLayout_24.addWidget(self.listWidget_Vis_Res_Ani_fSele)

        self.pushButton_Vis_Res_Ani_Apply = QtWidgets.QPushButton(self.verticalLayoutWidget_22)
        self.pushButton_Vis_Res_Ani_Apply.setObjectName("pushButton_Vis_Res_Ani_Apply")
        self.verticalLayout_24.addWidget(self.pushButton_Vis_Res_Ani_Apply)

        self.graphicsView_Vis_Res_Ani_Disp = QtWidgets.QGraphicsView(self.page_20)
        self.graphicsView_Vis_Res_Ani_Disp.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Res_Ani_Disp.setObjectName("graphicsView_Vis_Res_Ani_Disp")

        self.horizontalLayoutWidget_24 = QtWidgets.QWidget(self.page_20)
        self.horizontalLayoutWidget_24.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_24.setObjectName("horizontalLayoutWidget_24")

        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_24)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")

        self.pushButton_Vis_Res_Ani_Replay = QtWidgets.QPushButton(self.horizontalLayoutWidget_24)
        self.pushButton_Vis_Res_Ani_Replay.setObjectName("pushButton_Vis_Res_Ani_Replay")
        self.horizontalLayout_29.addWidget(self.pushButton_Vis_Res_Ani_Replay)

        self.pushButton_Vis_Res_Ani_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_24)
        self.pushButton_Vis_Res_Ani_Save.setObjectName("pushButton_Vis_Res_Ani_Save")
        self.horizontalLayout_29.addWidget(self.pushButton_Vis_Res_Ani_Save)

        self.stackedWidget_Vis_Res_PageAni.addWidget(self.page_20)
        self.stackedWidget_Vis_Res_7.addWidget(self.page_18)
        self.stackedWidget_Vis_Res_PagecSca.addWidget(self.page_3)

        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.stackedWidget_Vis_Res_PagecSca.addWidget(self.page_8)

        self.horizontalLayoutWidget = QtWidgets.QWidget(self.Resistivity)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 721, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")

        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")

        self.radioButton_Vis_Res_cSche = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_Vis_Res_cSche.setObjectName("radioButton_Vis_Res_cSche")
        self.horizontalLayout_6.addWidget(self.radioButton_Vis_Res_cSche)

        self.radioButton_Vis_Res_cSca = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_Vis_Res_cSca.setObjectName("radioButton_Vis_Res_cSca")
        self.horizontalLayout_6.addWidget(self.radioButton_Vis_Res_cSca)

        self.radioButton_Vis_Res_Ani = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.radioButton_Vis_Res_Ani.setObjectName("radioButton_Vis_Res_Ani")
        self.horizontalLayout_6.addWidget(self.radioButton_Vis_Res_Ani)

        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.Resistivity)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(460, 450, 271, 41))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")

        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")

        self.pushButton_Vis_Res_cSca_Replay = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_Vis_Res_cSca_Replay.setObjectName("pushButton_Vis_Res_cSca_Replay")
        self.horizontalLayout_13.addWidget(self.pushButton_Vis_Res_cSca_Replay)

        self.pushButton_Vis_Res_cSca_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.pushButton_Vis_Res_cSca_Save.setObjectName("pushButton_Vis_Res_cSca_Save")
        self.horizontalLayout_13.addWidget(self.pushButton_Vis_Res_cSca_Save)

        self.tabWidget_Vis_Wat.addTab(self.Resistivity, "")
        self.Water_Content = QtWidgets.QWidget()
        self.Water_Content.setObjectName("Water_Content")

        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.Water_Content)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(10, 0, 721, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.radioButton_Vis_Res_cSche_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_9)
        self.radioButton_Vis_Res_cSche_2.setObjectName("radioButton_Vis_Res_cSche_2")
        self.horizontalLayout_14.addWidget(self.radioButton_Vis_Res_cSche_2)
        self.radioButton_Vis_Res_cSca_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_9)
        self.radioButton_Vis_Res_cSca_2.setObjectName("radioButton_Vis_Res_cSca_2")
        self.horizontalLayout_14.addWidget(self.radioButton_Vis_Res_cSca_2)
        self.radioButton_Vis_Res_Ani_2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_9)
        self.radioButton_Vis_Res_Ani_2.setObjectName("radioButton_Vis_Res_Ani_2")
        self.horizontalLayout_14.addWidget(self.radioButton_Vis_Res_Ani_2)
        self.stackedWidget_Vis_Wat_PagecSche = QtWidgets.QStackedWidget(self.Water_Content)
        self.stackedWidget_Vis_Wat_PagecSche.setGeometry(QtCore.QRect(0, 40, 741, 441))
        self.stackedWidget_Vis_Wat_PagecSche.setObjectName("stackedWidget_Vis_Wat_PagecSche")
        self.page_33 = QtWidgets.QWidget()
        self.page_33.setObjectName("page_33")
        self.graphicsView_Vis_Wat_cSche_Disp = QtWidgets.QGraphicsView(self.page_33)
        self.graphicsView_Vis_Wat_cSche_Disp.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Wat_cSche_Disp.setObjectName("graphicsView_Vis_Wat_cSche_Disp")
        self.horizontalLayoutWidget_19 = QtWidgets.QWidget(self.page_33)
        self.horizontalLayoutWidget_19.setGeometry(QtCore.QRect(460, 400, 261, 41))
        self.horizontalLayoutWidget_19.setObjectName("horizontalLayoutWidget_19")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_19)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_Vis_Wat_cSche_Replay = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        self.pushButton_Vis_Wat_cSche_Replay.setObjectName("pushButton_Vis_Wat_cSche_Replay")
        self.horizontalLayout_24.addWidget(self.pushButton_Vis_Wat_cSche_Replay)
        self.pushButton_Vis_Wat_cSche_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_19)
        self.pushButton_Vis_Wat_cSche_Save.setObjectName("pushButton_Vis_Wat_cSche_Save")
        self.horizontalLayout_24.addWidget(self.pushButton_Vis_Wat_cSche_Save)
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.page_33)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_Vis_Wat_cSche_fSele = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_Vis_Wat_cSche_fSele.setObjectName("label_Vis_Wat_cSche_fSele")
        self.verticalLayout_17.addWidget(self.label_Vis_Wat_cSche_fSele)
        self.listWidget_Vis_Wat_cSche_fSele = QtWidgets.QListWidget(self.verticalLayoutWidget_15)
        self.listWidget_Vis_Wat_cSche_fSele.setObjectName("listWidget_Vis_Wat_cSche_fSele")
        self.verticalLayout_17.addWidget(self.listWidget_Vis_Wat_cSche_fSele)
        self.label_Vis_Wat_cSche_cSche = QtWidgets.QLabel(self.verticalLayoutWidget_15)
        self.label_Vis_Wat_cSche_cSche.setObjectName("label_Vis_Wat_cSche_cSche")
        self.verticalLayout_17.addWidget(self.label_Vis_Wat_cSche_cSche)
        self.listWidget_Vis_Wat_cSche_cSche = QtWidgets.QListWidget(self.verticalLayoutWidget_15)
        self.listWidget_Vis_Wat_cSche_cSche.setObjectName("listWidget_Vis_Wat_cSche_cSche")
        self.verticalLayout_17.addWidget(self.listWidget_Vis_Wat_cSche_cSche)
        self.pushButton_Vis_Wat_cSche_Apply = QtWidgets.QPushButton(self.verticalLayoutWidget_15)
        self.pushButton_Vis_Wat_cSche_Apply.setObjectName("pushButton_Vis_Wat_cSche_Apply")
        self.verticalLayout_17.addWidget(self.pushButton_Vis_Wat_cSche_Apply)
        self.stackedWidget_Vis_Wat_PagecSche.addWidget(self.page_33)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget_Vis_Wat_PagecSca = QtWidgets.QStackedWidget(self.page)
        self.stackedWidget_Vis_Wat_PagecSca.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.stackedWidget_Vis_Wat_PagecSca.setObjectName("stackedWidget_Vis_Wat_PagecSca")
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.page_10)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_Vis_Res_fSele_4 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_Vis_Res_fSele_4.setObjectName("label_Vis_Res_fSele_4")
        self.verticalLayout_21.addWidget(self.label_Vis_Res_fSele_4)
        self.listWidget_Vis_Res_cSche_fSele_4 = QtWidgets.QListWidget(self.verticalLayoutWidget_19)
        self.listWidget_Vis_Res_cSche_fSele_4.setObjectName("listWidget_Vis_Res_cSche_fSele_4")
        self.verticalLayout_21.addWidget(self.listWidget_Vis_Res_cSche_fSele_4)
        self.label_Vis_Res_cSche_4 = QtWidgets.QLabel(self.verticalLayoutWidget_19)
        self.label_Vis_Res_cSche_4.setObjectName("label_Vis_Res_cSche_4")
        self.verticalLayout_21.addWidget(self.label_Vis_Res_cSche_4)
        self.listWidget_Vis_Res_cSche_cSche_4 = QtWidgets.QListWidget(self.verticalLayoutWidget_19)
        self.listWidget_Vis_Res_cSche_cSche_4.setObjectName("listWidget_Vis_Res_cSche_cSche_4")
        self.verticalLayout_21.addWidget(self.listWidget_Vis_Res_cSche_cSche_4)
        self.pushButton_Vis_Res_cSche_Apply_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_19)
        self.pushButton_Vis_Res_cSche_Apply_3.setObjectName("pushButton_Vis_Res_cSche_Apply_3")
        self.verticalLayout_21.addWidget(self.pushButton_Vis_Res_cSche_Apply_3)
        self.graphicsView_Vis_Res_cSche_Disp_4 = QtWidgets.QGraphicsView(self.page_10)
        self.graphicsView_Vis_Res_cSche_Disp_4.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Res_cSche_Disp_4.setObjectName("graphicsView_Vis_Res_cSche_Disp_4")
        self.horizontalLayoutWidget_23 = QtWidgets.QWidget(self.page_10)
        self.horizontalLayoutWidget_23.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_23.setObjectName("horizontalLayoutWidget_23")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_23)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.pushButton_Vis_Res_cSche_Replay_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_23)
        self.pushButton_Vis_Res_cSche_Replay_4.setObjectName("pushButton_Vis_Res_cSche_Replay_4")
        self.horizontalLayout_28.addWidget(self.pushButton_Vis_Res_cSche_Replay_4)
        self.pushButton_Vis_Res_cSche_Save_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_23)
        self.pushButton_Vis_Res_cSche_Save_4.setObjectName("pushButton_Vis_Res_cSche_Save_4")
        self.horizontalLayout_28.addWidget(self.pushButton_Vis_Res_cSche_Save_4)
        self.stackedWidget_Vis_Wat_PagecSca.addWidget(self.page_10)
        self.page_40 = QtWidgets.QWidget()
        self.page_40.setObjectName("page_40")
        self.graphicsView_Vis_Res_cSca_Disp_5 = QtWidgets.QGraphicsView(self.page_40)
        self.graphicsView_Vis_Res_cSca_Disp_5.setGeometry(QtCore.QRect(140, 20, 591, 391))
        self.graphicsView_Vis_Res_cSca_Disp_5.setObjectName("graphicsView_Vis_Res_cSca_Disp_5")
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.page_40)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_Vis_Res_cSca_fSele_5 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.label_Vis_Res_cSca_fSele_5.setObjectName("label_Vis_Res_cSca_fSele_5")
        self.verticalLayout_22.addWidget(self.label_Vis_Res_cSca_fSele_5)
        self.listWidget_Vis_Res_cSca_fSele_5 = QtWidgets.QListWidget(self.verticalLayoutWidget_20)
        self.listWidget_Vis_Res_cSca_fSele_5.setObjectName("listWidget_Vis_Res_cSca_fSele_5")
        self.verticalLayout_22.addWidget(self.listWidget_Vis_Res_cSca_fSele_5)
        self.label_Vis_Res_cSca_cSca_4 = QtWidgets.QLabel(self.verticalLayoutWidget_20)
        self.label_Vis_Res_cSca_cSca_4.setObjectName("label_Vis_Res_cSca_cSca_4")
        self.verticalLayout_22.addWidget(self.label_Vis_Res_cSca_cSca_4)
        self.listWidget_Vis_Res_cSca_cSca_4 = QtWidgets.QListWidget(self.verticalLayoutWidget_20)
        self.listWidget_Vis_Res_cSca_cSca_4.setObjectName("listWidget_Vis_Res_cSca_cSca_4")
        self.verticalLayout_22.addWidget(self.listWidget_Vis_Res_cSca_cSca_4)
        self.pushButton_Vis_Res_cSca_Apply_3 = QtWidgets.QPushButton(self.verticalLayoutWidget_20)
        self.pushButton_Vis_Res_cSca_Apply_3.setObjectName("pushButton_Vis_Res_cSca_Apply_3")
        self.verticalLayout_22.addWidget(self.pushButton_Vis_Res_cSca_Apply_3)
        self.stackedWidget_Vis_Wat_PagecSca.addWidget(self.page_40)
        self.page_41 = QtWidgets.QWidget()
        self.page_41.setObjectName("page_41")
        self.verticalLayoutWidget_25 = QtWidgets.QWidget(self.page_41)
        self.verticalLayoutWidget_25.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_25.setObjectName("verticalLayoutWidget_25")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_25)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_Vis_Res_Ani_fSele_4 = QtWidgets.QLabel(self.verticalLayoutWidget_25)
        self.label_Vis_Res_Ani_fSele_4.setObjectName("label_Vis_Res_Ani_fSele_4")
        self.verticalLayout_27.addWidget(self.label_Vis_Res_Ani_fSele_4)
        self.listWidget_Vis_Res_Ani_fSele_4 = QtWidgets.QListWidget(self.verticalLayoutWidget_25)
        self.listWidget_Vis_Res_Ani_fSele_4.setObjectName("listWidget_Vis_Res_Ani_fSele_4")
        self.verticalLayout_27.addWidget(self.listWidget_Vis_Res_Ani_fSele_4)
        self.pushButton_Vis_Res_Ani_Apply_4 = QtWidgets.QPushButton(self.verticalLayoutWidget_25)
        self.pushButton_Vis_Res_Ani_Apply_4.setObjectName("pushButton_Vis_Res_Ani_Apply_4")
        self.verticalLayout_27.addWidget(self.pushButton_Vis_Res_Ani_Apply_4)
        self.graphicsView_Vis_Res_Ani_Disp_4 = QtWidgets.QGraphicsView(self.page_41)
        self.graphicsView_Vis_Res_Ani_Disp_4.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Res_Ani_Disp_4.setObjectName("graphicsView_Vis_Res_Ani_Disp_4")
        self.horizontalLayoutWidget_27 = QtWidgets.QWidget(self.page_41)
        self.horizontalLayoutWidget_27.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_27.setObjectName("horizontalLayoutWidget_27")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_27)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.pushButton_Vis_Res_Ani_Replay_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_27)
        self.pushButton_Vis_Res_Ani_Replay_4.setObjectName("pushButton_Vis_Res_Ani_Replay_4")
        self.horizontalLayout_32.addWidget(self.pushButton_Vis_Res_Ani_Replay_4)
        self.pushButton_Vis_Res_Ani_Save_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget_27)
        self.pushButton_Vis_Res_Ani_Save_4.setObjectName("pushButton_Vis_Res_Ani_Save_4")
        self.horizontalLayout_32.addWidget(self.pushButton_Vis_Res_Ani_Save_4)
        self.stackedWidget_Vis_Wat_PagecSca.addWidget(self.page_41)
        self.stackedWidget_Vis_Wat_PagecSche.addWidget(self.page)
        self.page_34 = QtWidgets.QWidget()
        self.page_34.setObjectName("page_34")
        self.stackedWidget_Vis_Res_10 = QtWidgets.QStackedWidget(self.page_34)
        self.stackedWidget_Vis_Res_10.setGeometry(QtCore.QRect(0, 0, 741, 441))
        self.stackedWidget_Vis_Res_10.setObjectName("stackedWidget_Vis_Res_10")
        self.page_35 = QtWidgets.QWidget()
        self.page_35.setObjectName("page_35")
        self.graphicsView_13 = QtWidgets.QGraphicsView(self.page_35)
        self.graphicsView_13.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.horizontalLayoutWidget_20 = QtWidgets.QWidget(self.page_35)
        self.horizontalLayoutWidget_20.setGeometry(QtCore.QRect(460, 400, 261, 41))
        self.horizontalLayoutWidget_20.setObjectName("horizontalLayoutWidget_20")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_20)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.pushButton_43 = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.pushButton_43.setObjectName("pushButton_43")
        self.horizontalLayout_25.addWidget(self.pushButton_43)
        self.pushButton_44 = QtWidgets.QPushButton(self.horizontalLayoutWidget_20)
        self.pushButton_44.setObjectName("pushButton_44")
        self.horizontalLayout_25.addWidget(self.pushButton_44)
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.page_35)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_18.addWidget(self.label_19)
        self.listWidget_23 = QtWidgets.QListWidget(self.verticalLayoutWidget_16)
        self.listWidget_23.setObjectName("listWidget_23")
        self.verticalLayout_18.addWidget(self.listWidget_23)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_16)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_18.addWidget(self.label_20)
        self.listWidget_24 = QtWidgets.QListWidget(self.verticalLayoutWidget_16)
        self.listWidget_24.setObjectName("listWidget_24")
        self.verticalLayout_18.addWidget(self.listWidget_24)
        self.pushButton_45 = QtWidgets.QPushButton(self.verticalLayoutWidget_16)
        self.pushButton_45.setObjectName("pushButton_45")
        self.verticalLayout_18.addWidget(self.pushButton_45)
        self.stackedWidget_Vis_Res_10.addWidget(self.page_35)
        self.page_36 = QtWidgets.QWidget()
        self.page_36.setObjectName("page_36")
        self.stackedWidget_Vis_Wat_PageAni = QtWidgets.QStackedWidget(self.page_36)
        self.stackedWidget_Vis_Wat_PageAni.setGeometry(QtCore.QRect(0, -10, 741, 441))
        self.stackedWidget_Vis_Wat_PageAni.setObjectName("stackedWidget_Vis_Wat_PageAni")
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.page_9)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.label_Vis_Wat_cSche_fSele_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_Vis_Wat_cSche_fSele_2.setObjectName("label_Vis_Wat_cSche_fSele_2")
        self.verticalLayout_19.addWidget(self.label_Vis_Wat_cSche_fSele_2)
        self.listWidget_Vis_Wat_cSche_fSele_2 = QtWidgets.QListWidget(self.verticalLayoutWidget_17)
        self.listWidget_Vis_Wat_cSche_fSele_2.setObjectName("listWidget_Vis_Wat_cSche_fSele_2")
        self.verticalLayout_19.addWidget(self.listWidget_Vis_Wat_cSche_fSele_2)
        self.label_Vis_Wat_cSche_cSche_2 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        self.label_Vis_Wat_cSche_cSche_2.setObjectName("label_Vis_Wat_cSche_cSche_2")
        self.verticalLayout_19.addWidget(self.label_Vis_Wat_cSche_cSche_2)
        self.listWidget_Vis_Wat_cSche_cSche_2 = QtWidgets.QListWidget(self.verticalLayoutWidget_17)
        self.listWidget_Vis_Wat_cSche_cSche_2.setObjectName("listWidget_Vis_Wat_cSche_cSche_2")
        self.verticalLayout_19.addWidget(self.listWidget_Vis_Wat_cSche_cSche_2)
        self.pushButton_Vis_Wat_cSche_Apply_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_17)
        self.pushButton_Vis_Wat_cSche_Apply_2.setObjectName("pushButton_Vis_Wat_cSche_Apply_2")
        self.verticalLayout_19.addWidget(self.pushButton_Vis_Wat_cSche_Apply_2)
        self.graphicsView_Vis_Wat_cSche_Disp_2 = QtWidgets.QGraphicsView(self.page_9)
        self.graphicsView_Vis_Wat_cSche_Disp_2.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Wat_cSche_Disp_2.setObjectName("graphicsView_Vis_Wat_cSche_Disp_2")
        self.horizontalLayoutWidget_21 = QtWidgets.QWidget(self.page_9)
        self.horizontalLayoutWidget_21.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_21.setObjectName("horizontalLayoutWidget_21")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_21)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.pushButton_Vis_Wat_cSche_Replay_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_21)
        self.pushButton_Vis_Wat_cSche_Replay_2.setObjectName("pushButton_Vis_Wat_cSche_Replay_2")
        self.horizontalLayout_26.addWidget(self.pushButton_Vis_Wat_cSche_Replay_2)
        self.pushButton_Vis_Wat_cSche_Save_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_21)
        self.pushButton_Vis_Wat_cSche_Save_2.setObjectName("pushButton_Vis_Wat_cSche_Save_2")
        self.horizontalLayout_26.addWidget(self.pushButton_Vis_Wat_cSche_Save_2)
        self.stackedWidget_Vis_Wat_PageAni.addWidget(self.page_9)
        self.page_38 = QtWidgets.QWidget()
        self.page_38.setObjectName("page_38")
        self.graphicsView_Vis_Wat_cSca_Disp = QtWidgets.QGraphicsView(self.page_38)
        self.graphicsView_Vis_Wat_cSca_Disp.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Wat_cSca_Disp.setObjectName("graphicsView_Vis_Wat_cSca_Disp")
        self.horizontalLayoutWidget_22 = QtWidgets.QWidget(self.page_38)
        self.horizontalLayoutWidget_22.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_22.setObjectName("horizontalLayoutWidget_22")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_22)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.pushButton_Vis_Wat_cSca_Replay = QtWidgets.QPushButton(self.horizontalLayoutWidget_22)
        self.pushButton_Vis_Wat_cSca_Replay.setObjectName("pushButton_Vis_Wat_cSca_Replay")
        self.horizontalLayout_27.addWidget(self.pushButton_Vis_Wat_cSca_Replay)
        self.pushButton_Vis_Wat_cSca_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_22)
        self.pushButton_Vis_Wat_cSca_Save.setObjectName("pushButton_Vis_Wat_cSca_Save")
        self.horizontalLayout_27.addWidget(self.pushButton_Vis_Wat_cSca_Save)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.page_38)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_Vis_Wat_cSca_fSele = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.label_Vis_Wat_cSca_fSele.setObjectName("label_Vis_Wat_cSca_fSele")
        self.verticalLayout_20.addWidget(self.label_Vis_Wat_cSca_fSele)
        self.listWidget_Vis_Wat_cSca_fSele = QtWidgets.QListWidget(self.verticalLayoutWidget_18)
        self.listWidget_Vis_Wat_cSca_fSele.setObjectName("listWidget_Vis_Wat_cSca_fSele")
        self.verticalLayout_20.addWidget(self.listWidget_Vis_Wat_cSca_fSele)
        self.label_Vis_Wat_cSca_cSca = QtWidgets.QLabel(self.verticalLayoutWidget_18)
        self.label_Vis_Wat_cSca_cSca.setObjectName("label_Vis_Wat_cSca_cSca")
        self.verticalLayout_20.addWidget(self.label_Vis_Wat_cSca_cSca)
        self.listWidget_Vis_Wat_cSca_cSca = QtWidgets.QListWidget(self.verticalLayoutWidget_18)
        self.listWidget_Vis_Wat_cSca_cSca.setObjectName("listWidget_Vis_Wat_cSca_cSca")
        self.verticalLayout_20.addWidget(self.listWidget_Vis_Wat_cSca_cSca)
        self.pushButton_Vis_Wat_cSca_Apply = QtWidgets.QPushButton(self.verticalLayoutWidget_18)
        self.pushButton_Vis_Wat_cSca_Apply.setObjectName("pushButton_Vis_Wat_cSca_Apply")
        self.verticalLayout_20.addWidget(self.pushButton_Vis_Wat_cSca_Apply)
        self.stackedWidget_Vis_Wat_PageAni.addWidget(self.page_38)
        self.page_39 = QtWidgets.QWidget()
        self.page_39.setObjectName("page_39")
        self.verticalLayoutWidget_24 = QtWidgets.QWidget(self.page_39)
        self.verticalLayoutWidget_24.setGeometry(QtCore.QRect(10, 10, 121, 431))
        self.verticalLayoutWidget_24.setObjectName("verticalLayoutWidget_24")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_24)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label_Vis_Wat_Ani_fSele = QtWidgets.QLabel(self.verticalLayoutWidget_24)
        self.label_Vis_Wat_Ani_fSele.setObjectName("label_Vis_Wat_Ani_fSele")
        self.verticalLayout_26.addWidget(self.label_Vis_Wat_Ani_fSele)
        self.listWidget_Vis_Wat_Ani_fSele = QtWidgets.QListWidget(self.verticalLayoutWidget_24)
        self.listWidget_Vis_Wat_Ani_fSele.setObjectName("listWidget_Vis_Wat_Ani_fSele")
        self.verticalLayout_26.addWidget(self.listWidget_Vis_Wat_Ani_fSele)
        self.pushButton_Vis_Wat_Ani_Apply = QtWidgets.QPushButton(self.verticalLayoutWidget_24)
        self.pushButton_Vis_Wat_Ani_Apply.setObjectName("pushButton_Vis_Wat_Ani_Apply")
        self.verticalLayout_26.addWidget(self.pushButton_Vis_Wat_Ani_Apply)
        self.graphicsView_Vis_Wat_Ani_Disp = QtWidgets.QGraphicsView(self.page_39)
        self.graphicsView_Vis_Wat_Ani_Disp.setGeometry(QtCore.QRect(140, 10, 591, 391))
        self.graphicsView_Vis_Wat_Ani_Disp.setObjectName("graphicsView_Vis_Wat_Ani_Disp")
        self.horizontalLayoutWidget_26 = QtWidgets.QWidget(self.page_39)
        self.horizontalLayoutWidget_26.setGeometry(QtCore.QRect(460, 400, 271, 41))
        self.horizontalLayoutWidget_26.setObjectName("horizontalLayoutWidget_26")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_26)
        self.horizontalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.pushButton_Vis_Wat_Ani_Replay = QtWidgets.QPushButton(self.horizontalLayoutWidget_26)
        self.pushButton_Vis_Wat_Ani_Replay.setObjectName("pushButton_Vis_Wat_Ani_Replay")
        self.horizontalLayout_31.addWidget(self.pushButton_Vis_Wat_Ani_Replay)
        self.pushButton_Vis_Wat_Ani_Save = QtWidgets.QPushButton(self.horizontalLayoutWidget_26)
        self.pushButton_Vis_Wat_Ani_Save.setObjectName("pushButton_Vis_Wat_Ani_Save")
        self.horizontalLayout_31.addWidget(self.pushButton_Vis_Wat_Ani_Save)
        self.stackedWidget_Vis_Wat_PageAni.addWidget(self.page_39)
        self.stackedWidget_Vis_Res_10.addWidget(self.page_36)
        self.page_37 = QtWidgets.QWidget()
        self.page_37.setObjectName("page_37")
        self.stackedWidget_Vis_Res_10.addWidget(self.page_37)
        self.stackedWidget_Vis_Wat_PagecSche.addWidget(self.page_34)
        self.tabWidget_Vis_Wat.addTab(self.Water_Content, "")
        self.horizontalLayout_5.addWidget(self.tabWidget_Vis_Wat)
        self.tabWidget.addTab(self.Visualization, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)



        self.setWindowTitle("Data Visualization")
        self.setGeometry(100, 100, 800, 600)

        self.central_widget = QWidget()
        self.setCentralWidget(self.central_widget)

        self.layout = QHBoxLayout()
        self.central_widget.setLayout(self.layout)

        self.setup_menu()
        self.setup_resistivity_ui()
        self.setup_visualization_ui()



    #the stacked widgets of ResistivityVisualization
    def stackedWidg_res(self):
        layout = QVBoxLayout()

        #using radio button for mapping corresponding widget
        self.radioButton_Vis_Res_Ani = QRadioButton(self.stackedWidget_Vis_Res_PageAni)
        self.radioButton_Vis_Res_cSche = QRadioButton(self.stackedWidget_Vis_Res_7)
        self.radioButton_Vis_Res_cSca = QRadioButton(self.stackedWidget_Vis_Res_PagecSca)


        self.radioButton_Vis_Res_Ani.setChecked(True)

        self.radioButton_Vis_Res_Ani.toggled.connect(self.display_stack)
        self.radioButton_Vis_Res_cSche.toggled.connect(self.display_stack)
        self.radioButton_Vis_Res_cSca.toggled.connect(self.display_stack)

        layout.addWidget(self.radioButton_Vis_Res_Ani)
        layout.addWidget(self.radioButton_Vis_Res_cSche)
        layout.addWidget(self.radioButton_Vis_Res_cSca)


        self.stack_res = QStackedWidget()
        self.stack_res.addWidget(self.stackedWidget_Vis_Res_PageAni)
        self.stack_res.addWidget(self.stackedWidget_Vis_Res_7)
        self.stack_res.addWidget(self.stackedWidget_Vis_Res_PagecSca)

        layout.addWidget(self.stack_res)
        self.setLayout(layout)

    def display_stack(self):
        if self.radioButton_Vis_Res_Ani.isChecked():
                self.stack_res.setCurrentIndex(0)
        elif self.radioButton_Vis_Res_cSche.isChecked():
                self.stack_res.setCurrentIndex(1)
        elif self.radioButton_Vis_Res_cSca.isChecked():
                self.stack_res.setCurrentIndex(2)

    #the stacked widgets of WaterContentVisualization
    def stackedWidg_wat(self):
        layout = QVBoxLayout()

        self.radioButton_Wat_Res_Ani = QRadioButton(self.stackedWidget_Vis_Wat_PageAni)
        self.radioButton_Wat_Res_cSche = QRadioButton(self.stackedWidget_Vis_Wat_7)
        self.radioButton_Wat_Res_cSca = QRadioButton(self.stackedWidget_Vis_Wat_PagecSca)

        self.radioButton_Wat_Res_Ani.setChecked(True)

        self.radioButton_Wat_Res_Ani.toggled.connect(self.display_stack)
        self.radioButton_Wat_Res_cSche.toggled.connect(self.display_stack)
        self.radioButton_Wat_Res_cSca.toggled.connect(self.display_stack)

        layout.addWidget(self.radioButton_Wat_Res_Ani)
        layout.addWidget(self.radioButton_Wat_Res_cSche)
        layout.addWidget(self.radioButton_Wat_Res_cSca)

        self.stack_wat = QStackedWidget()
        self.stack_wat.addWidget(self.stackedWidget_Vis_Wat_PageAni)
        self.stack_wat.addWidget(self.stackedWidget_Vis_Wat_7)
        self.stack_wat.addWidget(self.stackedWidget_Vis_Wat_PagecSca)

        layout.addWidget(self.stack_wat)
        self.setLayout(layout)


    def display_stack(self):
        if self.radioButton_Vis_Res_Ani.isChecked():
                self.stack_res.setCurrentIndex(0)
        elif self.radioButton_Vis_Res_cSche.isChecked():
                self.stack_res.setCurrentIndex(1)
        elif self.radioButton_Vis_Res_cSca.isChecked():
                self.stack_res.setCurrentIndex(2)



#sort png files based on dates which are the partial name of these png files
class DateSortProxyModel(QSortFilterProxyModel):
    def lessThan(self, left, right):
        left_date_str = left.data().split('_')[0]
        right_date_str = right.data().split('_')[0]
        return left_date_str < right_date_str

        #the path of this project as well as the folder of these png files
        project_folder_path = '.'

        all_files = os.listdir(project_folder_path)
        filtered_files = [f for f in all_files if f.endswith('_res.png')]

        model = QStringListModel()
        model.setStringList(filtered_files)

        proxyModel = DateSortProxyModel()
        proxyModel.setSourceModel(model)

        view = QListView()
        view.setModel(proxyModel)
        view.show()

        proxyModel.sort(0)

#generate the time-serial animation for display
class AnimatedGifLabel(QLabel):
        def setMovie(self, movie):
                super().setMovie(movie)
                movie.start()

        def setPixmap(self, pixmap):
                self._pixmap = pixmap
                super().setPixmap(pixmap)

        def mousePressEvent(self, event):
                if self.movie():
                        self.setPixmap(self._pixmap)
                        self.setMovie(None)
                else:
                        self.setPixmap(None)
                        self.setMovie(self._movie)

#generate the time-serial gif for saving files
class GifApp(QWidget):
        def __init__(self):
                super().__init__()

                self.layout = QVBoxLayout()
                self.gif_label = AnimatedGifLabel(self)
                self.apply_button = QPushButton('Apply', self)
                self.play_button = QPushButton('Play', self)
                self.save_button = QPushButton('Save', self)

                self.layout.addWidget(self.gif_label)
                self.layout.addWidget(self.apply_button)
                self.layout.addWidget(self.play_button)
                self.layout.addWidget(self.save_button)
                self.setLayout(self.layout)

                self.apply_button.clicked.connect(self.generate_gif)
                self.play_button.clicked.connect(self.play_gif)
                self.save_button.clicked.connect(self.save_gif)

        #generate time-serial gif file
        def generate_gif(self):
                project_folder_path = './project_folder/'
                all_files = os.listdir(project_folder_path)
                filtered_files = sorted(
                        [os.path.join(project_folder_path, f) for f in all_files if f.endswith('_res.png')])

                with imageio.get_writer('output.gif', mode='I') as writer:
                        for filename in filtered_files:
                                image = imageio.imread(filename)
                                writer.append_data(image)

                movie = QImageReader('output.gif')
                self.gif_label.setMovie(movie)

        #replay the gif file
        def play_gif(self):
                if self.gif_label.movie():
                        self.gif_label.movie().jumpToFrame(0)

        #saving the gif file
        def save_gif(self):
                options = QFileDialog.Options()
                filePath, _ = QFileDialog.getSaveFileName(self, "Save Gif", "",
                                                          "GIF Files (*.gif);;All Files (*)", options=options)
                if filePath:
                        os.rename('output.gif', filePath)





        def setup_menu(self):
                self.menu_bar = self.menuBar()
                self.visualisation_menu = self.menu_bar.addMenu("Visualization")
                self.resistivity_action = self.visualisation_menu.addAction("Resistivity")
                self.water_content_action = self.visualisation_menu.addAction("Water Content")

                def setup_resistivity_ui(self):
                self.resistivity_widget = QWidget()
                self.layout.addWidget(self.resistivity_widget)
                self.resistivity_layout = QHBoxLayout()
                self.resistivity_widget.setLayout(self.resistivity_layout)

                self.file_list_widget = QListWidget()
                self.color_scheme_list_widget = QListWidget()
                self.display_button = QPushButton("Display")
                self.apply_button = QPushButton("Apply")
                self.save_button = QPushButton("Save")
                self.fullscreen_button = QPushButton("Full Screen")
                self.mode_enlarge_checkbox = QCheckBox("Mode Enlarge")
                self.time_serial_animation_checkbox = QCheckBox("Time-Serial Animation")

                self.resistivity_layout.addWidget(self.file_list_widget, 3)
                self.resistivity_layout.addWidget(self.color_scheme_list_widget, 1)
                self.resistivity_layout.addWidget(self.display_button)
                self.resistivity_layout.addWidget(self.apply_button)
                self.resistivity_layout.addWidget(self.save_button)
                self.resistivity_layout.addWidget(self.fullscreen_button)
                self.resistivity_layout.addWidget(self.mode_enlarge_checkbox)
                self.resistivity_layout.addWidget(self.time_serial_animation_checkbox)

                self.resistivity_action.triggered.connect(self.show_resistivity_ui)
                self.time_serial_animation_checkbox.stateChanged.connect(self.toggle_animation_ui)

        def setup_visualization_ui(self):
                self.visualization_widget = QWidget()
                self.layout.addWidget(self.visualization_widget)
                self.visualization_layout = QVBoxLayout()
                self.visualization_widget.setLayout(self.visualization_layout)

                self.image_label = QLabel()
                self.visualization_layout.addWidget(self.image_label)
                self.image_label.setAlignment(Qt.AlignCenter)

                self.resistivity_widget.setVisible(False)
                self.visualization_widget.setVisible(False)

                self.animation_timer = QTimer()
                self.animation_timer.timeout.connect(self.update_animation)
                self.animation_images = []
                self.animation_index = 0

        def show_resistivity_ui(self):
                self.set_current_widget(self.resistivity_widget)

        def toggle_animation_ui(self):
                if self.time_serial_animation_checkbox.isChecked():
                        self.file_list_widget.setSelectionMode(QListWidget.MultiSelection)
                        self.apply_button.clicked.connect(self.start_animation)
                        else:
                        self.file_list_widget.setSelectionMode(QListWidget.SingleSelection)
                        self.apply_button.clicked.disconnect(self.start_animation)
                        self.stop_animation()

        def set_current_widget(self, widget):
                self.visualization_widget.setVisible(False)
                self.resistivity_widget.setVisible(False)
                widget.setVisible(True)

        def start_animation(self):
                selected_items = self.file_list_widget.selectedItems()
                if not selected_items:
                        return

                self.animation_images = []
                for item in selected_items:
                        file_path = item.text()
                        image = cv2.imread(file_path)
                        if image is not None:
                                self.animation_images.append(image)

                if self.animation_images:
                        self.animation_index = 0
                        self.animation_timer.start(100)  # Adjust the delay as needed

        def stop_animation(self):
                self.animation_timer.stop()

        def update_animation(self):
                if self.animation_images:
                        frame = self.animation_images[self.animation_index]
                        height, width, channel = frame.shape
                        bytes_per_line = 3 * width
                        q_image = QImage(frame.data, width, height, bytes_per_line, QImage.Format_RGB888)
                        pixmap = QPixmap.fromImage(q_image)
                        self.image_label.setPixmap(pixmap)
                        self.animation_index = (self.animation_index + 1) % len(self.animation_images)








        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 981, 26))
        self.menubar.setObjectName("menubar")
        self.menuProject = QtWidgets.QMenu(self.menubar)
        self.menuProject.setObjectName("menuProject")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuOption = QtWidgets.QMenu(self.menubar)
        self.menuOption.setObjectName("menuOption")
        MainWindow.setMenuBar(self.menubar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionGuidline = QtWidgets.QAction(MainWindow)
        self.actionGuidline.setObjectName("actionGuidline")
        self.actionContract = QtWidgets.QAction(MainWindow)
        self.actionContract.setObjectName("actionContract")
        self.menuProject.addAction(self.actionNew)
        self.menuProject.addAction(self.actionOpen)
        self.menuProject.addAction(self.actionSave)
        self.menuHelp.addAction(self.actionGuidline)
        self.menuHelp.addAction(self.actionContract)
        self.menubar.addAction(self.menuProject.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(4)
        self.tabWidget_2.setCurrentIndex(1)
        self.tabWidget_Vis_Wat.setCurrentIndex(1)
        self.stackedWidget_Vis_Res_PagecSca.setCurrentIndex(1)
        self.stackedWidget_Vis_Res_7.setCurrentIndex(1)
        self.stackedWidget_Vis_Res_PageAni.setCurrentIndex(1)
        self.stackedWidget_Vis_Wat_PagecSche.setCurrentIndex(2)
        self.stackedWidget_Vis_Wat_PagecSca.setCurrentIndex(1)
        self.stackedWidget_Vis_Res_10.setCurrentIndex(1)
        self.stackedWidget_Vis_Wat_PageAni.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Import"))
        self.pushButton.setText(_translate("MainWindow", "Choose your file"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Data), _translate("MainWindow", "Data"))
        self.pushButton_2.setText(_translate("MainWindow", "Clean Data"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Pre_processing), _translate("MainWindow", "Pre_processing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Importing), _translate("MainWindow", "Importing"))
        self.pushButton_4.setText(_translate("MainWindow", "Apply"))
        self.pushButton_8.setText(_translate("MainWindow", "Save"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Geometry:</p></body></html>"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">start</p></body></html>"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">end</p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mesh:</p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Quality</p></body></html>"))
        self.textEdit_6.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Area</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Domain_Mesh), _translate("MainWindow", "Domain and Mesh"))
        self.textEdit_8.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">maxIter:</p></body></html>"))
        self.textEdit_9.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lam:</p></body></html>"))
        self.textEdit_10.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">dPhi:</p></body></html>"))
        self.pushButton_5.setText(_translate("MainWindow", "Apply"))
        self.pushButton_9.setText(_translate("MainWindow", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Inversion), _translate("MainWindow", "Inversion"))
        self.textEdit_11.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt;\">Temperture</span></p></body></html>"))
        self.pushButton_12.setText(_translate("MainWindow", "Calculate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Water Content"))
        self.pushButton_Vis_Res_cSca_Replay_2.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Res_cSca_Save_2.setText(_translate("MainWindow", "Save"))
        self.label_Vis_Res_cSca_fSele_2.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Res_cSca_cSca.setText(_translate("MainWindow", "Color Scale"))
        self.pushButton_Vis_Res_cSca_Apply.setText(_translate("MainWindow", "Apply"))
        self.pushButton_26.setText(_translate("MainWindow", "Replay"))
        self.pushButton_27.setText(_translate("MainWindow", "Save"))
        self.label_11.setText(_translate("MainWindow", "File Selection"))
        self.pushButton_28.setText(_translate("MainWindow", "Apply"))
        self.label_Vis_Res_fSele.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Res_cSche.setText(_translate("MainWindow", "Color Scheme"))
        self.pushButton_Vis_Res_cSche_Apply.setText(_translate("MainWindow", "Apply"))
        self.pushButton_Vis_Res_cSche_Replay.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Res_cSche_Save.setText(_translate("MainWindow", "Save"))
        self.label_Vis_Res_cSca_fSele.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Res_cSca_cSca_3.setText(_translate("MainWindow", "Color Scale"))
        self.pushButton_Vis_Res_cSca_Apply_2.setText(_translate("MainWindow", "Apply"))
        self.label_Vis_Res_Ani_fSele.setText(_translate("MainWindow", "File Selection"))
        self.pushButton_Vis_Res_Ani_Apply.setText(_translate("MainWindow", "Apply"))
        self.pushButton_Vis_Res_Ani_Replay.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Res_Ani_Save.setText(_translate("MainWindow", "Save"))
        self.radioButton_Vis_Res_cSche.setText(_translate("MainWindow", "Color Scheme"))
        self.radioButton_Vis_Res_cSca.setText(_translate("MainWindow", "Custom Color Scale"))
        self.radioButton_Vis_Res_Ani.setText(_translate("MainWindow", "Time-Serial Animation"))
        self.pushButton_Vis_Res_cSca_Replay.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Res_cSca_Save.setText(_translate("MainWindow", "Save"))
        self.tabWidget_Vis_Wat.setTabText(self.tabWidget_Vis_Wat.indexOf(self.Resistivity), _translate("MainWindow", "Resistivity"))
        self.radioButton_Vis_Res_cSche_2.setText(_translate("MainWindow", "Color Scheme"))
        self.radioButton_Vis_Res_cSca_2.setText(_translate("MainWindow", "Custom Color Scale"))
        self.radioButton_Vis_Res_Ani_2.setText(_translate("MainWindow", "Time-Serial Animation"))
        self.pushButton_Vis_Wat_cSche_Replay.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Wat_cSche_Save.setText(_translate("MainWindow", "Save"))
        self.label_Vis_Wat_cSche_fSele.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Wat_cSche_cSche.setText(_translate("MainWindow", "Color Scheme"))
        self.pushButton_Vis_Wat_cSche_Apply.setText(_translate("MainWindow", "Apply"))
        self.label_Vis_Res_fSele_4.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Res_cSche_4.setText(_translate("MainWindow", "Color Scheme"))
        self.pushButton_Vis_Res_cSche_Apply_3.setText(_translate("MainWindow", "Apply"))
        self.pushButton_Vis_Res_cSche_Replay_4.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Res_cSche_Save_4.setText(_translate("MainWindow", "Save"))
        self.label_Vis_Res_cSca_fSele_5.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Res_cSca_cSca_4.setText(_translate("MainWindow", "Color Scale"))
        self.pushButton_Vis_Res_cSca_Apply_3.setText(_translate("MainWindow", "Apply"))
        self.label_Vis_Res_Ani_fSele_4.setText(_translate("MainWindow", "File Selection"))
        self.pushButton_Vis_Res_Ani_Apply_4.setText(_translate("MainWindow", "Apply"))
        self.pushButton_Vis_Res_Ani_Replay_4.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Res_Ani_Save_4.setText(_translate("MainWindow", "Save"))
        self.pushButton_43.setText(_translate("MainWindow", "Replay"))
        self.pushButton_44.setText(_translate("MainWindow", "Save"))
        self.label_19.setText(_translate("MainWindow", "File Selection"))
        self.label_20.setText(_translate("MainWindow", "Color Scale"))
        self.pushButton_45.setText(_translate("MainWindow", "Apply"))
        self.label_Vis_Wat_cSche_fSele_2.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Wat_cSche_cSche_2.setText(_translate("MainWindow", "Color Scheme"))
        self.pushButton_Vis_Wat_cSche_Apply_2.setText(_translate("MainWindow", "Apply"))
        self.pushButton_Vis_Wat_cSche_Replay_2.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Wat_cSche_Save_2.setText(_translate("MainWindow", "Save"))
        self.pushButton_Vis_Wat_cSca_Replay.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Wat_cSca_Save.setText(_translate("MainWindow", "Save"))
        self.label_Vis_Wat_cSca_fSele.setText(_translate("MainWindow", "File Selection"))
        self.label_Vis_Wat_cSca_cSca.setText(_translate("MainWindow", "Color Scale"))
        self.pushButton_Vis_Wat_cSca_Apply.setText(_translate("MainWindow", "Apply"))
        self.label_Vis_Wat_Ani_fSele.setText(_translate("MainWindow", "File Selection"))
        self.pushButton_Vis_Wat_Ani_Apply.setText(_translate("MainWindow", "Apply"))
        self.pushButton_Vis_Wat_Ani_Replay.setText(_translate("MainWindow", "Replay"))
        self.pushButton_Vis_Wat_Ani_Save.setText(_translate("MainWindow", "Save"))
        self.tabWidget_Vis_Wat.setTabText(self.tabWidget_Vis_Wat.indexOf(self.Water_Content), _translate("MainWindow", "Water Content"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Visualization), _translate("MainWindow", "Visualization"))
        self.menuProject.setTitle(_translate("MainWindow", "Project"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuOption.setTitle(_translate("MainWindow", "Option"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionGuidline.setText(_translate("MainWindow", "Guidline"))
        self.actionContract.setText(_translate("MainWindow", "Contract"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
